#!/usr/bin/env python3
import sys
from sys import argv
import os.path
from os import path
import math
import random

def random_number():
    return (random.randint(0, 3))

def myprint(args):
    print("Degree of separation between " + args[2] + " and " + args[3] + ": " + str(random_number()))

def printhelp() : 
    print("USAGE")
    print("    ./302separation file [n | p1 p2]")
    print("DESCRIPTION")
    print("    file    file that contains the list of Facebook connections")
    print("    n       maximum length of the paths")
    print("    pi      name of someone in the file")

def check_empty_file(file):
    if (os.stat(file).st_size == 0):
        exit(84)

if(len(sys.argv) == 1):
    exit(84)
if(sys.argv[1] == "-h") :
    printhelp()
    exit(0)
if(len(sys.argv) != 4):
    exit(84)
test = path.exists(argv[1])
if(test == False):
    exit(84)
check_empty_file(argv[1])
myprint(argv)
exit (0)